AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvType:
    Description: Environment type
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must specify prod or test

  InstanceType:
    Description: Instance type
    Default: c5.xlarge
    Type: String
    AllowedValues:
      - c5.xlarge
      - c5.2xlarge

Conditions:
  IsProduction: !Equals
    - !Ref EnvType
    - prod
    
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-1234567890abcdef0
      InstanceType: !Ref InstanceType   # First reference to InstanceType (Parameter)
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: IsProduction    # Condition reference to IsProduction (Condition)
    Properties:
      InstanceId: !Ref EC2Instance    # Second reference to EC2Instance (Resource)
      VolumeId: !Ref NewVolume    # Third reference to NewVolume (Resource)
      Device: /dev/sdh
  NewVolume:
    Type: AWS::EC2::Volume
    Condition: IsProduction    # Condition reference to IsProduction (Condition)
    Properties:
      Size: 100
      AvailabilityZone: !GetAtt
        - EC2Instance    # Fourth reference to EC2Instance (Resource)
        - AvailabilityZone